### ISSUE TITLE
Fails on pytorch/examples/mnist/main.py

### ISSUE THREAD

**Issue by dov** [jacobkimmel/pytorch_modelsize#1]
While trying to figure out why the mnist example takes up 16GB of CPU on my machine, I tried running the pytorch_model size on it, like in your example. It failed as follows:

```
$ python3 main.py --no-cuda
Traceback (most recent call last):
  File "main.py", line 80, in <module>
    print(se.estimate_size())
  File "/space/pub-repos/pytorch-examples/mnist/pytorch_modelsize.py", line 76,
in estimate_size
    self.get_output_sizes()
  File "/space/pub-repos/pytorch-examples/mnist/pytorch_modelsize.py", line 40,
in get_output_sizes
    out = m(input_)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", li
ne 371, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/linear.py", li
ne 55, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/functional.py", line 9
74, in linear
    output = input.matmul(weight.t())
RuntimeError: size mismatch, m1: [25600 x 20], m2: [320 x 50] at /space/pub-repo
s/pytorch/aten/src/TH/generic/THTensorMath.c:2010

```

See: https://github.com/pytorch/examples/blob/master/mnist/main.py

**Comment by dov** [comment]
Looking at the code again, it is not clear how your size estimater could possibly work in the general case since you are only considering the operators defined in `__init__()`. But this misses the actual use of any additional operators in the `forward()` method. E.g. for the mnist examples, the `forward()` uses `max_pool2()` which reduces the dimensionality. But your estimator misses those.

**Comment by jacobkimmel** [comment]
hey @dov, thanks for the comments.

The error you find is related to the same limitation you mention — the estimator can’t access `Functional` operators in `forward()`, so any that change dimensionality will lead to an error. 

To the best of my knowledge, there is no trivial way to assess the dimensionality changes of `Functional` operators in `forward()` on an individual basis, making it difficult to implement a size estimator as I have done for `nn.Module` attributes. If you have any ideas on that front, I’m open to PRs.

I’ll edit the repo to make this limitation clear, thanks!

**Comment by jacobkimmel** [comment]
Added language describing this limitation in the `README`
