### ISSUE TITLE
Cannot compute the size of a model with multiple layer types

### ISSUE THREAD

**Issue by Sanghyun-Hong** [jacobkimmel/pytorch_modelsize#2]
This tool does not work if we have a model with multiple layer types. As a simple example, if we use the MNIST sample [Link](https://github.com/pytorch/examples/tree/master/mnist), this script returns the error.

Need to be fixed as there's no model with only one layer type. [Fixed in [here](https://discuss.pytorch.org/t/gpu-memory-estimation-given-a-network/1713) as well]

**Comment by jacobkimmel** [comment]
The tool fails because a dimensionality change occurs outside a module in
`forward`. (See the call to `view`. There is no current way I know of to
identify arbitrary dimensionality changes not performed by a module.

This is noted in the README.
