### ISSUE TITLE
DenseNet InputSize

### ISSUE THREAD

**Issue by seedship** [jacobkimmel/pytorch_modelsize#5]
Let me start this post by saying I'm a newbie when it comes to deep learning, so please tell me any of my design decisions are wrong.

I'm using a pretrained densenet161 instance and I'm running into CUDA out of memory errors. I haven't disabled any of the requires_grad flags, so I am performing transfer learning onto the entire network. I replaced the last linear later with a different linear layer with a different number of outputs.

I wrote my own custom dataloader, which is returning images of dimension (B, H, W, C) = (8, 384, 512, 3). Densenet Requires (3xHxW) so in my training I processed the data like so and training works but is phenomenally slow in CPU.

```
            x = x.transpose(1, 3)
            x = x.transpose(2, 3)
```

I am trying to estimate the size of the densenet model on the GPU, so I am doing the following.

```
x = x.transpose(1, 3)
x = x.transpose(2, 3)
se = SizeEstimator(model, input_size=x.shape)
estimate = se.estimate_size()
```

However, I get the following error:
```
RuntimeError                              Traceback (most recent call last)

<ipython-input-25-88d642640bb8> in <module>
     12 x = x.transpose(2, 3)
     13 se = SizeEstimator(model, input_size=x.shape)
---> 14 estimate = se.estimate_size()
     15 print(estimate)

~/TUM/SS20/Model-Driven Approach for Robotics Perception/PapPercComp/pytorch_modelsize.py in estimate_size(self)
     74         '''Estimate model size in memory in megabytes and bits'''
     75         self.get_parameter_sizes()
---> 76         self.get_output_sizes()
     77         self.calc_param_bits()
     78         self.calc_forward_backward_bits()

~/TUM/SS20/Model-Driven Approach for Robotics Perception/PapPercComp/pytorch_modelsize.py in get_output_sizes(self)
     38         for i in range(1, len(mods)):
     39             m = mods[i]
---> 40             out = m(input_)
     41             out_sizes.append(np.array(out.size()))
     42             input_ = out

~/.local/lib/python3.8/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

~/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py in forward(self, input)
    343 
    344     def forward(self, input):
--> 345         return self.conv2d_forward(input, self.weight)
    346 
    347 class Conv3d(_ConvNd):

~/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py in conv2d_forward(self, input, weight)
    339                             weight, self.bias, self.stride,
    340                             _pair(0), self.dilation, self.groups)
--> 341         return F.conv2d(input, weight, self.bias, self.stride,
    342                         self.padding, self.dilation, self.groups)
    343 

RuntimeError: Given groups=1, weight of size 96 3 7 7, expected input[8, 2208, 12, 16] to have 3 channels, but got 2208 channels instead
```

I have tried various different combinations of transposing the dimensions, all to no avail. If it works for training, it should work here to determine the size of the model, right?

Thanks!

**Comment by seedship** [comment]
I have just looked at the other closed issues, and I imagine DenseNet probably also has functional operators that change the size of the input data?

**Comment by jacobkimmel** [comment]
Yes, most likely some dimensionality changes are happening outside of `model.modules()`. As of now, I don't believe there's any way to detect arbitrary dimensionality changes in the `forward()` method, so size estimation isn't possible.

I'd look at the `forward()` method of the model you're using and write a version that replaces any functional operators with modules. You can even use dummy modules for simple modification.

e.g. for `x_1 = x_0.view(-1, 1)`.

```
class ViewLayer(nn.Module):
  def __init__(self,):
    super(ViewLayer, self).__init__()

  def forward(self, x):
    return x.view(-1, 1)
```
